version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
build_script:
  - ps: ./scripts/build.ps1
environment:
  APPVEYOR_REPO_TAG: true
artifacts:
  - path: TurisSharp/bin/Release/netstandard1.4
    name: netstandard16
  - path: TurisSharp/bin/Release/net45
    name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
  - provider: NuGet
    api_key:
      secure: k7ur9xUUaAjsuqmjzB2+a6H3ycaO6JCXGnOvZbp7B0zHAWqqcNQYToeIMezy76iT
    on:
      branch: master
